config/routes.rb
Rails.application.routes.draw do

  root to: "sessions#new"

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :show] do 
    resources :check_ins, only: [:new]
    resources :tours, only: [:new]
  end

  resources :houses, only: [:index]

  resources :tours do 
    resources :check_ins, only: [:new, :create]    
  end

  resources :check_ins, only: [:index, :destroy]

  resources :check_ins do 
    post :report, on: :collection
  end

  namespace :api, defaults: {format: :json} do
    resources :tours, only: [:index] do  
      resources :check_ins, only: [:new, :create]
    end
    resources :tours
  end
  

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :permissions
	has_many :houses, through: :permissions, source: :house
	has_many :tours, through: :houses, source: :tours
	
	validates :username, presence: true
	validates :password_digest, presence: {message: "Password can't be blank"}
	validates :password, length: {minimum: 6, allow_nil: true}
	validates :session_token, presence: true

	after_initialize :ensure_session_token

	attr_reader :password

	def self.generate_session_token
		SecureRandom::urlsafe_base64(16)
	end

	def self.find_by_credentials(username, password)
		user = User.find_by_username(username)
		return nil if user.nil?
		user.is_password?(password) ? user : nil
	end

	def reset_session_token
		self.session_token = self.class.generate_session_token
		self.save!
		self.session_token #do I care about this?
	end

	def password=(password)
		@password = password
		self.password_digest = BCrypt::Password.create(password)
	end

	def is_password?(password)
		BCrypt::Password.new(self.password_digest).is_password?(password) 
	end

	def superuser?
		!!self.superuser
	end

	private

	def ensure_session_token
		self.session_token ||= self.class.generate_session_token
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :require_current_user!, except: [:create, :new]
	before_action :require_correct_user!, except: [:create, :new]

#might not want new or create user functions, since no signing up
#new users would be for creating new admin accounts, which probably shouldn't be necessary
	def new 
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		
		#might not want to render json just yet, check other app
		if @user.save
			login!(@user)
			redirect_to user_url(@user)
		else
			render json: @user.errors.full_messages
		end

	end

	def show
		#the instance variable isn't actually necessary here
		#double check this to make sure it works properly
		@user = User.find(current_user.id) #can also use params[:id]
		# @tour = current_user.tours.where
		render :show
	end

	private

	def user_params
		params.require(:user).permit(:username, :password)
	end

	def require_correct_user!
		user = User.find_by_id(params[:id])
		if current_user.session_token != user.session_token
			redirect_to user_url(current_user.id)
		end
	end

	def require_current_user!
		redirect_to new_session_url if current_user.nil?
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<a href="<%= new_tour_url %>" class="button huge new-tour-button" id="nextTourButton">Next Tour</a>

<script type="text/javascript">
	// 	writeDate();
	// window.setInterval(function(){
	// 	writeDate();
	// }, 60000)

	function writeDate() {
		var date = new Date();
		var datestr = formatDate(date);
		$("#nextTourButton").html(datestr);
	}

	function formatDate(date) {
	  var hours = date.getHours();
	  var minutes = date.getMinutes();
	  while (minutes % 15 != 0){
	  	minutes += 1
	  }
	  if (minutes === 60){
	  	minutes = 0
	  	hours += 1
	  }
	  var ampm = hours >= 12 ? 'pm' : 'am';
	  hours = hours % 12;
	  hours = hours ? hours : 12; // the hour '0' should be '12'
	  minutes = minutes < 10 ? '0'+minutes : minutes;
	  var strTime = hours + ':' + minutes + ' ' + ampm;
	  return strTime;
}
</script>