config/routes.rb
Rails.application.routes.draw do

  root to: "sessions#new"

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :show] do 
    resources :check_ins, only: [:new]
    resources :tours, only: [:new]
  end

  resources :houses, only: [:index]

  resources :tours do 
    resources :check_ins, only: [:new, :create]    
  end

  resources :check_ins, only: [:index, :destroy]

  resources :check_ins do 
    post :report, on: :collection
  end

  namespace :api, defaults: {format: :json} do
    resources :tours, only: [:index] do  
      resources :check_ins, only: [:new, :create]
    end
    resources :tours
  end
  

end

app/models/check_in.rb
class CheckIn < ActiveRecord::Base

	belongs_to :room
	belongs_to :tour
	has_one :house, through: :tour, source: :house

	validates :status, presence: true
	validates :tour_id, presence: true
	validates :room_id, presence: true

	def self.to_csv
		CSV.generate do |csv|
			columns = %w(status initials comment created_at)
			csv << columns
			all.each do |check_in|
				csv << check_in.attributes.values_at(*columns)
			end
		end
	end

	# validate :validate_house
	# validate :validate_new_room

	private
	# def validate_house
	# 	check = self
	# 	unless self.house.rooms.find_index {|r| r.id == check.room_id}
	# 		errors.add(:room_id, "Room must be in your building!")
	# 	end
	# end
end

app/controllers/api/check_ins_controller.rb
class Api::CheckInsController < ApplicationController

	def create
		@tour = Tour.find(params[:tour_id])
		@check_ins = @tour.check_ins.create(new_check_in_params[:check_in]).reject {|c| c.errors.empty?}

		if @check_ins.empty?
			if @tour.end_of_tour?
				render json: {redirect: edit_tour_url(@tour.id)}
			else
				render json: :success
			end
		else
			render json: @check_ins.first.errors.full_messages, status: :unprocessable_entity
			#come back to this for a better solution (how to display array of models' errors?)
		end
	end

	private

	def new_check_in_params
		params.require(:room).permit(:check_in => [:status, :initials, :comment, :room_id])
	end

end

app/controllers/check_ins_controller.rb
class CheckInsController < ApplicationController

	before_action :require_sign_in!

	def new
		@tour = Tour.find(params[:tour_id])
		@rooms = @tour.house.rooms.reverse
		@rooms_visited = @tour.check_ins.map {|c| c.room_id.to_s}.uniq

		render :backbone_new
	end

	# def create
	# 	@tour = Tour.find(params[:tour_id])
	# 	# room param might change with QR code
	# 	# @room = Room.find(check_in_params[:check_in].first[:room_id])
	# 	@check_ins = @tour.check_ins.create(new_check_in_params[:check_in]).reject {|c| c.errors.empty?}
	# 	if @check_ins.empty?
	# 		if @tour.end_of_tour?
	# 			redirect_to edit_tour_url(@tour.id)
	# 		else
	# 			render :new
	# 		end
	# 	else
	# 		flash.now[:errors] = @check_ins.errors.full_messages
	# 		render :new
	# 	end
	# end

	def index
		@houses = House.all
		@check_ins = CheckIn.order(tour_id: :desc).order(created_at: :desc).page(params[:page])
	end

	def report
		start_date = Date.parse(report_params[:start])
		end_date = Date.parse(report_params[:end])

		if end_date < start_date
			new_start = end_date
			end_date = start_date
			start_date = new_start
		end

		@check_ins = House.find(report_params[:house])
											.check_ins
											.where(created_at: start_date..end_date + 1.day)
																					
		send_data @check_ins.to_csv, type: "text/csv", filename: "report.csv", dispostion: "attachment"
		# render text: @check_ins.to_csv
	end

	private

	def new_check_in_params
		params.require(:room).permit(:check_in => [:status, :initials, :comment, :room_id])
	end

	def report_params
		params.require(:report).permit(:house, :start, :end)
	end
end

app/helpers/check_ins_helper.rb
module CheckInsHelper
end

app/views/check_ins/backbone_new.html.erb
<div id="check-in-main-content">
</div>

<script type="application/json" id="rooms-json">
	<%= @rooms.to_json.html_safe %>
</script>

<script type="application/json" id="tour-json">
	<%= @tour.to_json.html_safe %>
</script>	

<script type="application/json" id="visited-json">
	<%= @rooms_visited.to_json.html_safe %>
</script>	

<script type="text/javascript">
	$(document).ready(function(){
		var deferred = $.Deferred();
		var roomsJson = JSON.parse($("#rooms-json").html());
		var tourJson = JSON.parse($("#tour-json").html());
		var visitedJson = JSON.parse($("#visited-json").html());

	  deferred.done(BrandonApp.initialize).done(setwebcam).done(load);
	  deferred.resolve(roomsJson, tourJson, visitedJson, $("#check-in-main-content"));
});
</script>

app/views/check_ins/index.html.erb
<div class="row">
	<div class="small-6 columns small-centered">
		<h2>Completed Check-Ins</h2>
	</div>
</div>

<div class="row">
	<div class="small-3 columns">
		<h4>Report</h4>
		<%= form_tag(report_check_ins_url, {format: :csv, method: :post}) do %>
			<%= select_tag "report[house]", options_from_collection_for_select(@houses, "id", "house_name") %>
			<%= label(:report, :start, "Start Date") %>
			<%= date_field_tag("report[start]", nil, {required: true}) %>
			<%= label(:report, :end, "End Date") %>
			<%= date_field_tag("report[end]", nil, {required: true}) %>
			<%= submit_tag "Submit", {class: "button small"} %>
		<% end %>
	</div>

	<div class="small-9 columns">
		<table class="check-in-table">
			<thead>
				<tr>
					<td>Status</td>
					<td>Youth Initials</td>
					<td>Comment</td>
					<td>Room</td>
					<td>House</td>
					<td>Time</td>
				</tr>
			</thead>
			<tbody>
				<% @check_ins.each do |c| %>
					<tr>
						<td><%= c.status %></td>
						<td>
							<% unless c.initials.nil? %>
								<%= c.initials %>
							<% else %>
								N/A
							<% end %>
						</td>
						<td>
							<% unless c.comment.nil? %>
								<%= c.comment %>
							<% else %>
								N/A
							<% end %>
						</td>
						<td><%= c.room.room_name %></td>
						<td><%= c.tour.house.house_name %></td>
						<td><%= format_date_time(c.created_at) %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

<div id="paginateCheckIns">
	<%= paginate @check_ins %>
</div>

app/views/check_ins/new.html.erb
<!-- write helper method to multiply forms by number of beds in the room
need to use aA hack to send data as an 'array'
need that 'array' to create multiple check-in objects at controller level
(ActiveRecord takes an array to create multiple objects at once) -->

<h1>NEW CHECK IN</h1>

<!-- QR SCANNER GOES HERE sends ajax request (to room controller? to check_in controller API?) get num_beds for the room-->

	<!-- this will fill out based on QR scan; need to write javascript to multiply the forms by the room's num_beds value  -->

<form action="<%= tour_check_ins_url(@tour.id) %>" method="post">
	<%= auth_token %>

<div>
	FIRST CHECK_IN

	<select name="room[check_in][][status]">
		<option value="awake">Asleep</option>
		<option value="sleep">Awake</option>
		<option value="bathroom">Bathroom</option>
		<option value="pass">Pass</option>
		<option value="awol">AWOL</option>
	</select>

	<select name="room[check_in][][room_id]" id="check_in_room_select">
		<% @tour.house.rooms.reverse.each do |r| %>
			<option value="<%= r.id %>"><%= r.room_name %></option>
		<% end %>
	</select>

	<label for="check_in_initials">Initials</label>
	<input type="text" name="room[check_in][][initials]" id="check_in_initials">
	
	<label for="check_in_comment">Comment</label>
	<input type="textarea" name="room[check_in][][comment]" id="check_in_comment">
</div>

<br>

<div>
	SECOND CHECK_IN

	<select name="room[check_in][][status]">
		<option value="awake">Asleep</option>
		<option value="sleep">Awake</option>
		<option value="bathroom">Bathroom</option>
		<option value="pass">Pass</option>
		<option value="awol">AWOL</option>
	</select>

	<select name="room[check_in][][room_id]" id="check_in_room_select">
		<% @tour.house.rooms.reverse.each do |r| %>
			<option value="<%= r.id %>"><%= r.room_name %></option>
		<% end %>
	</select>

	<label for="check_in_initials">Initials</label>
	<input type="text" name="room[check_in][][initials]" id="check_in_initials">
	
	<label for="check_in_comment">Comment</label>
	<input type="textarea" name="room[check_in][][comment]" id="check_in_comment">
</div>

	<!-- this needs to take it's value through jQuery -->
	<!-- <input type="hidden" name="check_in[room_id]" value=""> -->

	<input type="submit" value="Submit Room">
</form>