config/routes.rb
Rails.application.routes.draw do

  root to: "sessions#new"

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :show] do 
    resources :check_ins, only: [:new]
    resources :tours, only: [:new]
  end

  resources :houses, only: [:index]

  resources :tours do 
    resources :check_ins, only: [:new, :create]    
  end

  resources :check_ins, only: [:index, :destroy]

  resources :check_ins do 
    post :report, on: :collection
  end

  namespace :api, defaults: {format: :json} do
    resources :tours, only: [:index] do  
      resources :check_ins, only: [:new, :create]
    end
    resources :tours
  end
  

end

app/models/tour.rb
class Tour < ActiveRecord::Base

	belongs_to :house
	has_many :check_ins

	has_attached_file :start_img, 
		styles: {small: "200x200#"},
		s3_protocol: "https",
		url: ":s3_domain_url",
		path: "/:class/:attachment/:id_partition/:style/:filename"

	has_attached_file :end_img,
		styles: {small: "200x200#"},
		s3_protocol: "https",
		url: ":s3_domain_url",
		path: "/:class/:attachment/:id_partition/:style/:filename"

	validates :house_id, presence: true
	#validates :timeslot, numericality: {only_integer: true, less_than: 4, greater_than_or_equal_to: 0}

	validates :start_img_fingerprint, uniqueness: {message: "Image must be unique!"}
	validates :end_img_fingerprint, uniqueness: {message: "Image must be unique!"}, allow_nil: true

	validates_attachment :start_img, presence: true, content_type: { content_type: ["image/png", "image/jpeg"]}
	validates_attachment :end_img, content_type: { content_type: ["image/png", "image/jpeg"]}

	# need to find robust way of enforcing that a room is not checked twice!
	def end_of_tour?
		self.check_ins.count == self.expected_check_ins
	end
	
	def expected_check_ins
		checks =  0
		self.house.rooms.each do |r|
			checks += r.num_beds
		end
		checks
	end

	# def validate_new_room(room_id)
	# 	if self.check_ins.find_index { |el| el.room_id == room_id }
	# 		false
	# 	else
	# 		true
	# 	end
	# end
	
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController

	before_action :require_sign_in!

	def index
		@tours = Tour.order(id: :desc).page(params[:page]).per(10)
	end

	def new 
		@houses = House.all
		# @timeslots = get_tour_time_slots
	end

	def create
		@tour = Tour.new(new_tour_params)
		if @tour.save
			redirect_to new_tour_check_in_url(@tour)
		else
			flash.now[:errors] = @tour.errors.full_messages
			@houses = House.all
			# @timeslots = get_tour_time_slots
			render :new
		end
	end

	def edit
		@tour = Tour.find(params[:id])
	end

	def update
		@tour = Tour.find(params[:id])
		@tour.completed = true
		
		if @tour.update(edit_tour_params)
			redirect_to user_url(current_user.id)
		else
			flash.now[:errors] = @tour.errors.full_messages
			render :edit
		end
	end

	private

	def new_tour_params
		params.require(:tour).permit(:house_id, :start_img)#, :timeslot)
	end

	def edit_tour_params
		params.require(:tour).permit(:end_img)
	end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/edit.html.erb
<div class="row">
	<div class="small-8 columns small-centered">
		<h2>End Tour</h2>
	</div>
</div>

<div class="row">
	<div class="small-8 columns small-centered">
		<form action="<%= tour_url %>" method="post" enctype="multipart/form-data">
			<%= update_method_input %>
			<%= auth_token %>

			<input type="file" name="tour[end_img]" id="take-picture" accept='image/png, image/jpeg' required>
			<input type="submit" value="Upload" class="button">
		</form>
	</div>
</div>

app/views/tours/index.html.erb
<div class="row">
	<div class="small-5 columns small-centered">
		<h2>Tour Review</h2>
	</div>
</div>

<script type="text/javascript">
	var brokenImage = function(image){
		$(image).attr("id", "broken-image");
		$(image).next().attr("id", "show-span");
	}
</script>

<div class="row">
	<div class="small-10 columns small-centered">
		<table class="tour-table">
			<thead>
				<tr>
					<td>House</td>
					<td>Start Time</td>
					<td>Start Image</td>
					<td>End Time</td>
					<td>End Image</td>
				</tr>
			</thead>
			<tbody>
				<% @tours.each do |t| %>
					<tr>
						<td><%= t.house.house_name %></td>
						<td><%= format_date_time(t.created_at) %></td>
						<td>
							<%= image_tag t.start_img.url(:small), id:"", onerror: "brokenImage(this)" %>
							<span id="hide-span">
								<h3>Incomplete</h3>
							</span>
						</td>
						<td><%= format_date_time(t.updated_at) %></td>
						<td>
							<%= image_tag t.end_img.url(:small), id:"", onerror: "brokenImage(this)" %>
							<span id="hide-span">
								<h3>Incomplete</h3>
							</span>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

<div id="paginateTours">
	<%= paginate @tours %>
</div>

app/views/tours/new.html.erb
<h2>Start Tour</h2>

<form action="<%= tours_url %>" method="post" enctype="multipart/form-data">
	<%= auth_token %>

	<% if current_user.superuser? %>
		<select name="tour[house_id]" id="admin_house_select">
			<% @houses.each do |h| %>
				<option value="<%= h.id %>"><%= h.house_name %></option>
			<% end %>
		</select>
	<% else %>
		<input type="hidden" name="tour[house_id]" value="<%= current_user.houses.first.id %>">
	<% end %>

	<label for="take-picture">Take starting selfie</label>
	<input type="file" name="tour[start_img]" id="take-picture" accept='image/png, image/jpeg' capture>

	<input type="submit" value="Upload" class="button">
</form>