config/routes.rb
Rails.application.routes.draw do

  root to: "sessions#new"

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :show] do 
    resources :check_ins, only: [:new]
    resources :tours, only: [:new]
  end

  resources :houses, only: [:index]

  resources :tours do 
    resources :check_ins, only: [:new, :create]    
  end

  resources :check_ins, only: [:index, :destroy]

  resources :check_ins do 
    post :report, on: :collection
  end

  namespace :api, defaults: {format: :json} do
    resources :tours, only: [:index] do  
      resources :check_ins, only: [:new, :create]
    end
    resources :tours
  end
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

	  <title>Brandon BedCheck</title>

    <%= stylesheet_link_tag    "application" %>
		<%= stylesheet_link_tag "print", media: "print" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
		<% if !current_user.nil? %>
			<nav class="top-bar" data-topbar role="navigation">
				<section class="top-bar-section">
          <ul class="title-area left">
            <li class="name">
              <h1><a href="#">Brandon Bed Check</a></h1>
            </li>
            <li class="divider"></li>
            <li><a href="#"><%= current_user.username %></a></li>
          </ul>

					<ul class="right">
						<li class="divider"></li>
						<li><a href="<%= user_url(current_user.id) %>">New Tour</a></li>
						<li class="divider"></li>
						<% if current_user.superuser? %>
							<li><a href="<%= houses_url %>">In Progress Tours</a></li>
							<li class="divider"></li>
							<li><a href="<%= check_ins_url %>">Check-In Review</a></li>
							<li class="divider"></li>
							<li><a href="<%= tours_url %>">Tour Review</a></li>
							<li class="divider"></li>
						<% end %>
						<li class="has-form">
							<form action="<%= session_url %>" method="post">
								<input type="hidden" name="_method" value="delete">
								<%= auth_token %>
								<button class="button tiny alert">Logout</button>
							</form>
						</li>
					</ul>
				</section>
			</nav>
		<% end %>

		<% if flash.now[:errors] %>
		<div class="row">
			<section id="errors" class="small-8 columns small-centered">
				<% flash.now[:errors].each do |e| %>
				<%= e %>
				<br>
				<% end %>
			</section>
		</div>
		<% end %>

    <%= yield %>

  </body>
</html>